# Generated by Django 3.0.5 on 2020-12-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=40)),
                ('edad', models.IntegerField(default=0)),
                ('comentario', models.TextField(default=None, null=True)),
                ('direccion', models.CharField(default=None, max_length=40)),
                ('pais', models.CharField(choices=[('FRA', 'Francia'), ('CHI', 'Chile'), ('BRA', 'Brasil'), ('ARG', 'Argentina'), ('PER', 'Peru')], max_length=3)),
            ],
        ),
    ]
