# Generated by Django 3.0.5 on 2020-12-06 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_persona'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PErsona',
            new_name='Personas',
        ),
    ]
