# Generated by Django 3.0.5 on 2020-12-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201206_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
