# Generated by Django 3.0.5 on 2020-12-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=40)),
                ('apodo', models.CharField(default=None, max_length=40)),
                ('telefono', models.IntegerField()),
                ('genero', models.CharField(choices=[('H', 'hombre'), ('F', 'mujer')], max_length=1)),
            ],
        ),
    ]
