# Generated by Django 3.0.5 on 2020-12-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
